---
compare build:
  image:
    # I just like pinning things, this version is latest, not special in any way
    name: alpine:3.10.3
    entrypoint: [""]
  tags:
    - docker
  script:
    # try building it and compare if resulting file is equal to what is commited.
    - cd build
    - ./build -file ../haproxy-spec.yaml > haproxy_spec_to_compare.yaml
    - diff -u haproxy_spec_to_compare.yaml haproxy_spec.yaml

yamllint:
  image:
    name: cytopia/yamllint:latest
    entrypoint: [""]
  tags:
    - docker
  script:
    # to test locally, run:  docker run --rm -v $(pwd):/data cytopia/yamllint .
    - /bin/sh -c "yamllint -f colored ."
    - chmod +x ./scripts/single-tag.sh
    - /bin/sh -c ./scripts/single-tag.sh
